#!/usr/bin/env bash

rm -f .vars.rc ids.rc all
find . \( -name '*.apk' -o -name '*.dex' -o -name '*.zip' -o -name '*.idsig' -o -name '*.jar' -o -name '*.aar' \) -delete
find pkg -name '*.java' -delete
